# Generated by Django 2.1.2 on 2018-12-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_auto_20181217_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(default=None, upload_to='authAPI/use_images'),
        ),
    ]
