# Generated by Django 2.1.2 on 2018-12-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0003_auto_20181222_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to=''),
        ),
    ]
