# Generated by Django 2.1.2 on 2018-12-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0004_auto_20181222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images'),
        ),
    ]
