# Generated by Django 2.1.2 on 2018-12-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0005_auto_20181222_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
